### ISSUE TITLE
First Issue!

### ISSUE THREAD

**Issue by iProgramMC** [GrowtopiaNoobs/GrowtopiaServer2#1]
Where the hell is the code?

**Comment by Koodaamo-MareDev** [comment]
Seems like someone didn't get the joke.

**Comment by iProgramMC** [comment]
What joke?

**Comment by iProgramMC** [comment]
Oops

**Comment by Koodaamo-MareDev** [comment]
I thought you were in the gtv3 team thingy. I also thought you didn't need extra code because you literally have everything in your server. Apparently I have been mistaken since clearly you are begging for code too.

**Comment by iProgramMC** [comment]
@MarmoriPelaa I am in the GTv3 team but I was just wondering what the new server will look like in terms of codebase. That is it. Extra tip: Growtopia Bot (or if you make your own, custom client) is the best tool for finding packets. You just gotta know how to do that.

**Comment by iProgramMC** [comment]
> you literally have everything in your server.


I used to beg for code but now I don't since I know how to make it work. Plus, the code I "begged" for was just client side stuff. I can make friends list work myself, no need to Ctrl+C and Ctrl+V

**Comment by GrowtopiaNoobs** [comment]
The code is here now.

**Comment by iProgramMC** [comment]
Alright
