### ISSUE TITLE
can i host my custom item in a separate Virtual Machine  

### ISSUE THREAD

**Issue by afnno** [GrowtopiaNoobs/GrowtopiaServer2#13]
Can i host my Custom item in other Virtual Machine and should i paste the cache file in server directory too? or just in  custom item hosting Virtual Machine?

**Comment by NotDark** [comment]
yes

**Comment by afnno** [comment]
> yes

So If i wanna change the news banner i just need to replace with my news_banner.rttex so will it update??

**Comment by afnno** [comment]
@NotDark

**Comment by iProgramMC** [comment]
You need to host the entire GT directory + everything that GT caches (easiest method is to just serve the growtopia folders but merge the folders inside cache with the folders inside the actual game dir)

You don't need a separate VM/VPS to host cache, you can use the same VPS that you run the web server which allows players to join your server (example xampp or nginx)
