### ISSUE TITLE
[INFO] - Growtopia Private Servers

### ISSUE THREAD

**Issue by RetroBooming** [GrowtopiaNoobs/GrowtopiaServer2#14]
Are Growtopia Private Servers still Working? Since GTS1 got DMCA' by ubi

**Comment by Furkan125** [comment]
Servers still working. You still can play private server.

**Comment by ahentati** [comment]
Can you share how I can bring up a private server?

Regards,
Akram

**Comment by Furkan125** [comment]
Did you mean how to bring up a private server with vps server ?

**Comment by RetroBooming** [comment]
i dont really play private servers i quit them im just curious?

**Comment by ahentati** [comment]
Yes, indeed. I can’t find this anywhere on how to bring up my own server ...

Regards,
Akram
