### ISSUE TITLE
[ERROR] CMake Windows

### ISSUE THREAD

**Issue by GuckTubeYT** [GrowtopiaNoobs/GrowtopiaServer2#8]
how to fix this

-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
-- The CXX compiler identification is MSVC 19.16.27038.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:16 (add_subdirectory):
  The source directory

    C:/Users/another/Desktop/GrowtopiaServer2-master/libs/enet

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "C:/Users/another/Desktop/GrowtopiaServer2-master/build/CMakeFiles/CMakeOutput.log".

C:\Users\another\Desktop\GrowtopiaServer2-master\build>msbuild ALL_BUILD.vcxproj /p:configuration=release
Microsoft (R) Build Engine version 4.8.3752.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: ALL_BUILD.vcxproj

**Comment by GrowtopiaNoobs** [comment]
You probably don't have inited submodules. Have you tried to build this project with `build.bat`?

**Comment by GuckTubeYT** [comment]
> You probably don't have inited submodules. Have you tried to build this project with `build.bat`?

yes

**Comment by GuckTubeYT** [comment]
i use build.bat for build it

**Comment by GuckTubeYT** [comment]
Nevermind, i must download Github for windows first, for build for CMake
